Repository finnishtransportagency/digiroad2, pull requests merged in 2018-11, with the labels that each got.

#1274 DROTH-1566 New feature to feedback tool
  UI/src/router.js
  UI/src/view/feedbackDataTool.js
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/feedback/FeedbackOperations.scala
Labels: merge ready

#1282 Droth 1544 data quality improvement using traffic sign data 3 pedestrian crossings
  UI/src/application.js
  UI/src/assetTypeConfiguration.js
  UI/src/controller/trafficSignsReadOnlyCollection.js
  UI/src/less/core/forms.less
  UI/src/less/site/asset-form.less
  UI/src/router.js
  UI/src/utils/backend-utils.js
  UI/src/view/navigationpanel/pedestrianCrossingBox.js
  UI/src/view/point_asset/directionalTrafficSignForm.js
  UI/src/view/point_asset/heightLimitForm.js
  UI/src/view/point_asset/obstacleForm.js
  UI/src/view/point_asset/pointAssetForm.js
  UI/src/view/point_asset/pointAssetLayer.js
  UI/src/view/point_asset/railwayCrossingForm.js
  UI/src/view/point_asset/servicePointForm.js
  UI/src/view/point_asset/trafficSignForm.js
  UI/src/view/point_asset/widthLimitForm.js
  UI/src/view/point_asset/widthLimitLabel.js
  UI/src/view/workListView.js
  UI/test/integration-tests.html
  UI/tmpl/index.html
  data-validator.bat
  data-validator.sh
  digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/PointAssetOperations.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/importer/PedestrianCrossingTierekisteriImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OraclePedestrianCrossingDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/process/AssetValidator.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/process/HazmatTransportProhibitionValidator.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/process/ManoeuvreValidator.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/process/PedestrianCrossingValidator.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/process/SevenRestrictionsLimitationValidator.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/PedestrianCrossingService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/AssetValidatorProcess.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/PedestrianCrossingValidatorSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/PedestrianCrossingServiceSpec.scala
Labels: merge ready

#1304 Droth 1679 municipality list missing from csv import
  UI/src/utils/backend-utils.js
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/dataimport/CsvDataImporter.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/dataimport/ImportDataApi.scala
  digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataimport/CsvDataImporterSpec.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/MunicipalityService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/MunicipalityDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OracleTrafficSignDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/LinearAssetService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficSignService.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficSignServiceSpec.scala
Labels: bug, merge ready

#1306 DROTH-1692 Quality list error with pedestrian crossing
  UI/src/application.js
  UI/src/assetTypeConfiguration.js
  UI/src/view/navigationpanel/pedestrianCrossingBox.js
  UI/src/view/point_asset/pointAssetForm.js
  UI/src/view/point_asset/pointAssetLayer.js
Labels: bug, merge ready

#1307 DROTH-1689 Undefined links on error list
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/InaccurateAssetDAO.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitService.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/dao/InaccurateAssetDaoSpec.scala
Labels: bug, merge ready

#1311 Droth 1704 administrative class doesnt refresh on cancel
  UI/src/controller/roadCollection.js
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
Labels: bug

#1309 DROTH-1694 Show traffic signs on turn restrictions: fix box
  UI/src/view/navigationpanel/manoeuvreBox.js
Labels: bug

#1308 Droth 1683 disabled bus stops when changing administrative class
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/MassTransitStopService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/TierekisteriBusStopStrategy.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/MassTransitStopServiceSpec.scala
Labels: bug
