Repository finnishtransportagency/digiroad2, pull requests merged in 2018-12, with the labels that each got.

#1279 Droth 1396 point of interest
  UI/images/service_points/airport.png
  UI/images/service_points/borderCrossingPoint.png
  UI/images/service_points/busStation.png
  UI/images/service_points/chargingPointElectricCars.png
  UI/images/service_points/customsControl.png
  UI/images/service_points/ferry.png
  UI/images/service_points/linearLabel_largeText_blue.png
  UI/images/service_points/linearLabel_largeText_yellow_red.png
  UI/images/service_points/loadingTerminalForCars.png
  UI/images/service_points/parking.png
  UI/images/service_points/parkingAreaBusesAndTrucks.png
  UI/images/service_points/parkingGarage.png
  UI/images/service_points/picnicSite.png
  UI/images/service_points/railwayStation.png
  UI/images/service_points/railwayStation2.png
  UI/images/service_points/subwayStation.png
  UI/images/service_points/taxiStation.png
  UI/src/assetTypeConfiguration.js
  UI/src/less/core/forms.less
  UI/src/less/site/action-panel.less
  UI/src/view/point_asset/pointAssetForm.js
  UI/src/view/point_asset/servicePointForm.js
  UI/src/view/point_asset/servicePointLabel.js
  UI/src/view/point_asset/signsLabel.js
  UI/src/view/point_asset/trafficSignLabel.js
  UI/src/view/point_asset/trafficSignReadOnlyLayer.js
  UI/test/integration-tests.html
  UI/tmpl/index.html
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/asset/asset.scala
  digiroad2-oracle/sql/service_points_charging_stations.sql
  digiroad2-oracle/sql/service_points_taxi_import.sql
  digiroad2-oracle/src/main/resources/db/migration/V184__add_new_property_on_service_point_value.sql
  digiroad2-oracle/src/main/resources/db/migration/V187__update_traffic_sign_enumerated_values.sql
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OracleServicePointDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/ServicePointService.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/ServicePointServiceSpec.scala
Labels: Flyway Version, merge ready

#1296 Droth 1045 ui improvements
  UI/src/assetTypeConfiguration.js
  UI/src/less/site/modals.less
  UI/src/view/dynamicAssetForm.js
  UI/src/view/linear_asset/linearAssetForm.js
  UI/src/view/linear_asset/manoeuvreForm.js
  UI/src/view/linear_asset/speedLimitForm.js
  UI/src/view/link_property/linkPropertyForm.js
  UI/src/view/point_asset/groupedPointAssetForm.js
  UI/src/view/point_asset/massTransitStopForm.js
  UI/src/view/point_asset/pointAssetForm.js
  UI/test/integration-tests/multiSegmentSpeedLimitSpec.js
  UI/test/integration-tests/singleSegmentSpeedLimitSpec.js
  UI/tmpl/index.html
Labels: merge ready

#1301 Droth 1646 closed down roads and bus stops
  UI/src/view/point_asset/massTransitStopForm.js
  UI/src/view/workListView.js
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/PointAssetOperations.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/MassTransitStopDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/TierekisteriBusStopStrategy.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/AssetDataImporter.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
Labels: merge ready

#1310 Droth 1519 new fields for private roads
  UI/src/model/selectedLinkProperty.js
  UI/src/view/link_property/linkPropertyForm.js
  digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/util/JsonSerializer.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
  digiroad2-oracle/src/main/resources/db/migration/V190__add_new_table_for_administrative_class_properties.sql
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/RoadLinkDAO.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/OracleLinearAssetDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/RoadLinkServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
Labels: Flyway Version
