Repository finnishtransportagency/digiroad2, pull requests merged in 2018-09, with the labels that each got.

#1259 Droth 1533 service point unformatted form
  UI/src/less/site/asset-form.less
  UI/src/model/selectedPointAsset.js
  UI/src/view/point_asset/pointAssetForm.js
Labels: bug

#1258 Droth 1529 text is missing from the feedback tool email
  UI/src/less/site/modals.less
  UI/src/view/feedbackDataTool.js
  UI/tmpl/index.html
Labels: bug

#1261 DROTH-1532 & DROTH-1542
  UI/src/assetTypeConfiguration.js
  UI/src/less/core/variables.less
  UI/src/less/site/action-panel.less
  UI/src/view/linear_asset/pavedRoadStyle.js
  UI/src/view/navigationpanel/pavedRoadBox.js
  digiroad2-oracle/src/main/resources/db/migration/V179__edit_enumerated_for_paved_road.sql
Labels: Flyway Version, bug

#1239 Droth 1419 creating update information for change api and tn its
  digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/ChangeApi.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/MunicipalityApi.scala
  digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/MunicipalityApiSpec.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/SpeedLimitFiller.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/OracleLinearAssetDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/OracleMaintenanceDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/OracleSpeedLimitDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/DynamicLinearAssetService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/LinearAssetService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/MaintenanceService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/NumericValueLinearAssetService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/OnOffLinearAssetService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/ProhibitionService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/RoadWidthService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/TextValueLinearAssetService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/PavedRoadService.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/dao/linearasset/OracleSpeedLimitDaoSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/DynamicLinearAssetServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/LinearAssetServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/OnOffLinearAssetServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/ProhibitionServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/RoadWidthServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/TextValueLinearAssetServiceSpec.scala
Labels: Test after merge

#1267 DROTH-1554 Polygon tool not working at linear assets
  UI/src/view/providers/selectToolControl.js
Labels: bug

#1272 DROTH-1570_Feedback_UI_improvements
  UI/src/less/site/asset-form.less
  UI/src/less/site/modals.less
  UI/src/view/feedbackApplicationTool.js
Labels: enhancement

#1273 Droth 1567 check functionality of update notification page
  UI/src/controller/userNotificationCollection.js
  UI/src/view/userNotificationPopup.js
  UI/tmpl/index.html
Labels: bug

#1275 DROTH-1574 vyöhyketieto field in kalpa api
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
Labels: bug

#1271 DROTH-1571 When logging as a municipality user the focus doesn't work
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
Labels: bug

#1276 Droth 1568 automatic process should expire and create new asset when have side adjustment
  digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
  digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/SpeedLimitUpdaterSpec.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/asset/asset.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/LinearAssetFiller.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/NumericalLimitFiller.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/SpeedLimitFiller.scala
  digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/linearasset/NumericalLimitFillerSpec.scala
  digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/linearasset/SpeedLimitFillerSpec.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/OracleLinearAssetDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/OracleSpeedLimitDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/DynamicLinearAssetService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/LinearAssetService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/ProhibitionService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/RoadWidthService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/PavedRoadService.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/DynamicLinearAssetServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/LinearAssetServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/ProhibitionServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/RoadWidthServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/PavedRoadServiceSpec.scala
Labels: merge ready
