Repository finnishtransportagency/digiroad2, pull requests merged in 2018-07, with the labels that each got.

#1214 Droth 1287 care class for oth
  UI/images/na.svg
  UI/src/application.js
  UI/src/assetTypeConfiguration.js
  UI/src/controller/careClassCollection.js
  UI/src/less/core/variables.less
  UI/src/less/site/action-panel.less
  UI/src/less/site/global.less
  UI/src/less/site/linear-asset-form.less
  UI/src/model/selectedLinearAsset.js
  UI/src/model/selectedLinearAssetFactory.js
  UI/src/view/dynamicAssetForm.js
  UI/src/view/linear_asset/careClassLayer.js
  UI/src/view/linear_asset/careClassStyle.js
  UI/src/view/linear_asset/linearAssetLayer.js
  UI/src/view/navigationpanel/careClassBox.js
  UI/src/view/navigationpanel/linearAssetBox.js
  UI/src/view/navigationpanel/navigationPanel.js
  UI/src/view/navigationpanel/roadLinkBox.js
  UI/src/view/navigationpanel/serviceRoadBox.js
  UI/src/view/navigationpanel/speedLimitBox.js
  UI/src/view/navigationpanel/winterSpeedLimitBox.js
  UI/test/integration-tests.html
  UI/tmpl/index.html
  digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/asset/asset.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/LinearAsset.scala
  digiroad2-oracle/src/main/resources/db/migration/V173__add_Hoitoluokat_asset_type.sql
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/TierekisteriGreenCareClassAssetClient.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/TierekisteriWinterCareClassAssetClient.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/importer/CareClassTierekisteriImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/importer/TierekisteriImporterOperations.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/DynamicLinearAssetDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/queries.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/DynamicLinearAssetService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/TierekisteriDataImporter.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/client/TierekisteriClientSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/dao/linearasset/DynamicLinearAssetDaoSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/DynamicLinearAssetServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/DynamicValueAssetServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/MultiValueAssetServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/TierekisteriImporterOperationsSpec.scala
Labels: merge ready

#1230 Droth 1434/1435/1436 serviceroad style form mass update fix
  UI/src/assetTypeConfiguration.js
  UI/src/model/selectedLinearAsset.js
  UI/src/model/selectedLinearAssetFactory.js
  UI/src/view/dynamicAssetForm.js
  UI/src/view/linear_asset/linearAssetForm.js
  UI/src/view/linear_asset/linearAssetLabel.js
  UI/src/view/linear_asset/linearAssetLayer.js
  UI/src/view/linear_asset/linearAssetMassUpdateDialog.js
  UI/src/view/linear_asset/piecewiseLinearAssetFormElements.js
  UI/src/view/linear_asset/prohibitionFormElements.js
  UI/src/view/linear_asset/serviceRoadStyle.js
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/TextValueLinearAssetService.scala
Labels: bug, merge ready

#1231 DROTH-1444 Wrong code values for special transport related road links
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/vvh/VVHClient.scala
Labels: bug, merge ready

#1232 Fix css scroll problems in firefox
  UI/src/less/site/global.less
  UI/src/view/dynamicAssetForm.js
  UI/src/view/linear_asset/careClassLayer.js
Labels: bug, merge ready

#1235 DROTH-1451 Dynamic value comparison
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/LinearAsset.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/DynamicValueAssetServiceSpec.scala
Labels: bug

#1219 Droth 1358 notification of production updates
  UI/src/application.js
  UI/src/controller/userNotificationCollection.js
  UI/src/less/site/modals.less
  UI/src/utils/backend-utils.js
  UI/src/view/userNotificationPopup.js
  UI/test/integration-tests.html
  UI/tmpl/index.html
  digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/user/DummyUserProvider.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/user/User.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/user/UserProvider.scala
  digiroad2-oracle/sql/user_notification_examples.sql
  digiroad2-oracle/src/main/resources/db/migration/V176__create_notification_table.sql
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/OracleUserProvider.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/UserNotificationDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/UserNotificationService.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/dao/OracleUserProviderSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/UserNotificationServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
Labels: Flyway Version, merge ready

#1244 DROTH-1479 Carrying capacity polygon selection
  UI/src/view/dynamicAssetForm.js
  UI/src/view/linear_asset/linearAssetMassUpdateDialog.js
Labels: bug

#1245 Droth 1476 traffic signs with liikvast information
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/TierekisteriTrafficSignAssetClient.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/importer/StateSpeedLimitTierekisteriImporter.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/client/TierekisteriClientSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/TierekisteriImporterOperationsSpec.scala
Labels: bug

#1243 Droth 1466 apply changes not set last adjustment timestamp and modified vvh generator
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/LinearAssetFiller.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/NumericalLimitFiller.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/SpeedLimitFiller.scala
  digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/linearasset/NumericalLimitFillerSpec.scala
  digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/linearasset/SpeedLimitFillerSpec.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/OracleLinearAssetDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/LinearAssetService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/MaintenanceService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/ProhibitionService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/RoadWidthService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/PavingService.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/LinearAssetServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/ProhibitionServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/RoadWidthServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/PavingServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
Labels: bug
