Repository finnishtransportagency/digiroad2, pull requests merged in 2018-04, with the labels that each got.

#1173 DROTH-1258 Wrong headline in unknonw speed limit list
  UI/src/view/municipalityWorkList.js
  UI/src/view/speedLimitWorkList.js
Labels: bug, merge ready

#1175 Droth 1260 performance unknown speed limit list
  UI/src/router.js
  UI/src/utils/backend-utils.js
  UI/src/view/municipalityWorkList.js
  UI/src/view/speedLimitWorkList.js
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/OracleSpeedLimitDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitService.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/dao/linearasset/OracleSpeedLimitDaoSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
Labels: merge ready

#1177 DROTH-1260 Performance unknown speed limit list: remove private roads
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/OracleSpeedLimitDao.scala
Labels: Improvement, urgent

#1178 Droth 1271 sometimes links are drawn thin line
  UI/src/application.js
  UI/src/utils/zoom-levels.js
  UI/src/view/linear_asset/groupedLinearAssetLayer.js
  UI/src/view/linear_asset/linearAssetLayer.js
  UI/src/view/linear_asset/manoeuvreLayer.js
  UI/src/view/linear_asset/speedLimitLayer.js
  UI/src/view/link_property/linkPropertyLayer.js
  UI/src/view/mapView.js
  UI/src/view/municipalityDisplay.js
  UI/src/view/point_asset/groupedPointAssetLayer.js
  UI/src/view/point_asset/massTransitStopLayer.js
  UI/src/view/point_asset/pointAssetLayer.js
  UI/src/view/point_asset/trafficSignReadOnlyLayer.js
  UI/src/view/providers/layer.js
  UI/src/view/providers/roadLayer.js
  UI/src/view/providers/selectToolControl.js
  UI/src/view/zoomBox.js
Labels: bug

#1162 Droth 1010 data improve using traffic sign data
  UI/src/controller/speedLimitsCollection.js
  UI/src/less/site/asset-form.less
  UI/src/model/selectedSpeedLimit.js
  UI/src/router.js
  UI/src/utils/backend-utils.js
  UI/src/view/linear_asset/speedLimitForm.js
  UI/src/view/workListView.js
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/ServiceRoadAPI.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/asset/asset.scala
  digiroad2-oracle/src/main/resources/db/migration/V157__create_inaccurate_asset_table.sql
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/PointAssetOperations.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/InaccurateAssetDAO.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/MunicipalityDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/OracleSpeedLimitDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OracleTrafficSignDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/process/SpeedLimitValidator.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficSignService.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/SpeedLimitValidatorSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/dao/InaccurateAssetDaoSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficSignServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
Labels: merge ready

#1164 Droth 1207 search with the passenger id for the bus stops
  UI/src/model/locationSearch.js
  UI/src/utils/backend-utils.js
  UI/src/utils/locationInputParser.js
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/MassTransitStopDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/MunicipalityDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/LinearAssetService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/MassTransitStopService.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/MassTransitStopServiceSpec.scala
Labels: merge ready

#1179 DROTH-1117 Issues with manoeuvre visualization
  UI/src/view/linear_asset/manoeuvreLayer.js
Labels: bug, need changes

#1183 DROTH-1286 A new vehicle type to be added vehicle asset
  UI/src/view/providers/assetFormElementsFactory.js
Labels: merge ready

#1187 DROTH-1289 Speed limit asset disappearing on the link when zooming or panning
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/SpeedLimitFiller.scala
Labels: bug, merge ready, urgent

#1181 Droth 1276 road address differences between oth and tr
  digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/Digiroad2ApiSpec.scala
  digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataimport/CsvImporterSpec.scala
  digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/GeometryUtilsSpec.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/TierekisteriMassTransitStopClient.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/RoadAddressDAO.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadAddressesService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/BusStopStrategy.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/MassTransitStopService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/TerminalBusStopStrategy.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/TierekisteriBusStopStrategy.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/GeometryTransform.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/client/TierekisteriClientSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/MassTransitStopServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/GeometryTransformSpec.scala
Labels: merge ready

#1188 DROTH-1301 Traffic signs not shown
  UI/src/router.js
  UI/src/view/linear_asset/speedLimitLayer.js
  UI/src/view/navigationpanel/speedLimitBox.js
  UI/src/view/providers/selectToolControl.js
Labels: bug, urgent

#1186 DROTH-1288 Traffic signs should have value validation on form
  UI/src/application.js
  UI/src/assetTypeConfiguration.js
  UI/src/utils/property-utils.js
  UI/src/view/point_asset/pointAssetForm.js
  UI/test/integration-tests.html
  UI/tmpl/index.html
Labels: bug

#1172 Droth 1187 railroad service road to be vizualised according to the huoltovastuu field
  UI/src/application.js
  UI/src/assetTypeConfiguration.js
  UI/src/less/site/action-panel.less
  UI/src/view/linear_asset/linearAssetLayer.js
  UI/src/view/linear_asset/serviceRoadLayer.js
  UI/src/view/linear_asset/serviceRoadStyle.js
  UI/src/view/navigationpanel/actionPanelBox.js
  UI/src/view/navigationpanel/serviceRoadBox.js
  UI/src/view/providers/assetLabel.js
  UI/test/integration-tests.html
  UI/tmpl/index.html
Labels: merge ready

#1169 Droth 1152 direction of traffic in roundabouts
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/dataimport/CsvDataImporter.scala
  digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataimport/CsvDataImporterSpec.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/GeometryUtils.scala
  digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/GeometryUtilsSpec.scala
  digiroad2-oracle/src/main/resources/db/migration/V162__add_property_traffic_direction.sql
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/RoadLinkDAO.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/VerificationDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/VerificationService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/RoundaboutProcessor.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/RoadLinkServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/VerificationServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/RoundaboutProcessorSpec.scala
Labels: merge ready

#1191 DROTH-1152 Fix direction when the Y position is equal
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/RoundaboutProcessor.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/RoundaboutProcessorSpec.scala
Labels: bug, merge ready

#1190 Droth 1303 bus stop information not shown
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/BusStopStrategy.scala
Labels: bug, merge ready
