Repository finnishtransportagency/digiroad2, pull requests merged in 2018-10, with the labels that each got.

#1250 Droth 1437 optional save for bus stops
  UI/src/authorizationpolicies/massTransitStopAuthorizationPolicy.js
  UI/src/model/selectedMassTransitStop.js
  UI/src/view/point_asset/massTransitStopForm.js
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/AssetPropertyConfiguration.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/MassTransitStopService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/TierekisteriBusStopStrategy.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/MassTransitStopServiceSpec.scala
Labels: merge ready

#1262 DROTH-1488 Text changes to CSV import form
  UI/csv_import.html
Labels: merge ready

#1268 Droth 1534 traffic signs corrections dropdown texts
  digiroad2-oracle/src/main/resources/db/migration/V184__update_traffic_sign_enumerated_values.sql
Labels: Flyway Version

#1286 Droth 1595 tierekisteri import improvement
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/importer/CareClassTierekisteriImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/importer/StateSpeedLimitTierekisteriImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/importer/TierekisteriImporterOperations.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/importer/TrafficSignTierekisteriImporter.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/TierekisteriImporterOperationsSpec.scala
Labels: Improvement, merge ready

#1288 DROTH-1611 (US 1413) Information source code value empty: Added overr…
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/PavedRoadService.scala
Labels: bug, merge ready

#1290 Droth 1609 municipality check mark
  UI/src/view/navigationpanel/actionPanelBox.js
  UI/src/view/navigationpanel/careClassBox.js
  UI/src/view/navigationpanel/carryingCapacityBox.js
  UI/src/view/navigationpanel/heightLimitationBox.js
  UI/src/view/navigationpanel/linearAssetBox.js
  UI/src/view/navigationpanel/manoeuvreBox.js
  UI/src/view/navigationpanel/massTransitStopBox.js
  UI/src/view/navigationpanel/navigationPanel.js
  UI/src/view/navigationpanel/pavedRoadBox.js
  UI/src/view/navigationpanel/pointAssetBox.js
  UI/src/view/navigationpanel/roadLinkBox.js
  UI/src/view/navigationpanel/serviceRoadBox.js
  UI/src/view/navigationpanel/speedLimitBox.js
  UI/src/view/navigationpanel/trSpeedLimitBox.js
  UI/src/view/navigationpanel/trafficSignBox.js
  UI/src/view/navigationpanel/weightLimitationBox.js
  UI/src/view/navigationpanel/widthLimitationBox.js
  UI/src/view/navigationpanel/winterSpeedLimitBox.js
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/VerificationDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/VerificationService.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/VerificationServiceSpec.scala
Labels: bug

#1287 DROTH-1605 increase tolerance for asset measures
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/importer/CareClassTierekisteriImporter.scala
Labels: bug

#1291 DROTH-1616 (US 1471) Traffic signs with no direction and not floating
  UI/src/utils/validity-directions.js
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficSignService.scala
Labels: bug

#1251 Droth 1447 update of turning restrictions by traffic signs
  UI/src/controller/trafficSignsCollection.js
  UI/src/model/selectedPointAsset.js
  digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/MunicipalityApi.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/GeometryUtils.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/Point.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/PointAssetOperations.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/importer/TierekisteriImporterOperations.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/importer/TrafficSignTierekisteriImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/OracleAssetDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/manoeuvre/ManoeuvreDAO.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OracleTrafficSignDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/ManoeuvreService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/DirectionalTrafficSignService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/HeightLimitService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/ObstacleService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/PedestrianCrossingService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/RailwayCrossingService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficLightService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficSignService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/WeightLimitService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/WidthLimitService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/MassTransitStopService.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/dao/linearasset/ManoeuvreDaoSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/RoadLinkServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/ManoeuvreServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/DirectionalTrafficSignServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/HeightLimitServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/ObstacleServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/PedestrianCrossingServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/RailwayCrossingServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficLightServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficSignServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/WeightLimitServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/WidthLimitServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
Labels: merge ready

#1257 Droth 1486 modification for csv import
  UI/csv_import.html
  UI/src/less/core/forms.less
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/dataimport/CsvDataImporter.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/dataimport/ImportDataApi.scala
  digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataimport/CsvDataImporterSpec.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/PointAssetOperations.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficSignService.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficSignServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
Labels: Flyway Version, merge ready

#1260 Droth 1504 correction to quality errors list
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/process/SpeedLimitValidator.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitService.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/SpeedLimitValidatorSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
Labels: merge ready

#1265 Droth 834 kalpa api for traffic signs
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/PointAssetOperations.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/TierekisteriClient.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/ObstacleService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/PedestrianCrossingService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/RailwayCrossingService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficLightService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficSignService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/MassTransitStopService.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficSignServiceSpec.scala
Labels: merge ready

#1284 Droth 1556 changing zoom level and labels
  UI/src/application.js
  UI/src/assetTypeConfiguration.js
  UI/src/controller/massTransitStopsCollection.js
  UI/src/main.js
  UI/src/utils/backend-utils.js
  UI/src/utils/zoom-levels.js
  UI/src/view/linear_asset/careClassStyle.js
  UI/src/view/linear_asset/linearAssetLayer.js
  UI/src/view/linear_asset/manoeuvreStyle.js
  UI/src/view/linear_asset/piecewiseLinearAssetStyle.js
  UI/src/view/linear_asset/serviceRoadStyle.js
  UI/src/view/linear_asset/speedLimitLayer.js
  UI/src/view/linear_asset/speedLimitStyle.js
  UI/src/view/linear_asset/trSpeedLimitStyle.js
  UI/src/view/linear_asset/winterSpeedLimitStyle.js
  UI/src/view/link_property/linkPropertyLayer.js
  UI/src/view/link_property/linkPropertyLayerStyles.js
  UI/src/view/point_asset/massTransitStopLayer.js
  UI/src/view/point_asset/pointAssetLayer.js
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/asset/asset.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/PointAssetOperations.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/MassTransitStopDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/MassTransitStopService.scala
Labels: need changes

#1292 Droth 1610 modified by timestamp is changed to vvh generated
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/PavedRoadService.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/PavedRoadServiceSpec.scala
Labels: bug

#1297 Droth 1640 separate not working
  UI/src/controller/linearAssetsCollection.js
  digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/MunicipalityApiSpec.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/DynamicLinearAssetService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/LinearAssetService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/MaintenanceService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/ProhibitionService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/RoadWidthService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/TextValueLinearAssetService.scala
Labels: bug
