Repository finnishtransportagency/digiroad2, pull requests merged in 2018-05, with the labels that each got.

#1195 Monitoring for OTH
  project/build.scala
  src/main/scala/fi/liikennevirasto/digiroad2/DigiroadServer.scala
  start.sh
Labels: urgent

#1180 DROTH-1206 adding field tasoristeystunnus to railroad crossings
  UI/src/assetTypeConfiguration.js
  UI/src/authorizationpolicies/manoeuvreAuthorizationPolicy.js
  UI/src/view/linear_asset/manoeuvreLayer.js
  UI/src/view/point_asset/pointAssetForm.js
  UI/src/view/speedLimitWorkList.js
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/MunicipalityApi.scala
  digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/MunicipalityApiSpec.scala
  digiroad2-oracle/sql/kauniainen_railway_crossings.sql
  digiroad2-oracle/src/main/resources/db/migration/V164__add_new_railway_crossing_text_property.sql
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OracleRailwayCrossingDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/queries.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/ObstacleService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/RailwayCrossingService.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/RailwayCrossingServiceSpec.scala
Labels: merge ready

#1167 Droth 1142 adding weight info on roads affected by thawing asset
  UI/images/linearLabel_largeText_yellow_red.png
  UI/images/warningLabel_red_yellow.png
  UI/src/asset-type-layer-specifications.js
  UI/src/assetTypeConfiguration.js
  UI/src/model/selectedLinearAssetFactory.js
  UI/src/view/assetFormFactory.js
  UI/src/view/linear_asset/linearAssetLabel.js
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
  digiroad2-oracle/src/main/resources/db/migration/V159__Add_new_proptertie_to_roads_affected_by_thawing.sql
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/TierekisteriDamagedByThawAssetClient.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/importer/DamagedByThawTierekisteriImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/LinearAssetService.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/TierekisteriImporterOperationsSpec.scala
Labels: Do not merge, need changes

#1199 DROTH-1300 Saving municipality page
  UI/src/view/municipalityWorkList.js
Labels: bug, merge ready

#1198 DROTH-1333 Saving affected by thawing
  UI/src/model/selectedLinearAsset.js
Labels: bug, merge ready

#1200 Droth 1336 kalpa reports error
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
Labels: bug, merge ready

#1197 Droth 1323 tn its speed limits overlapping data
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/OracleSpeedLimitDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitService.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/dao/linearasset/OracleSpeedLimitDaoSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitServiceSpec.scala
Labels: bug, merge ready

#1202 DROTH-1004 related : Added rule to batch
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
Labels: Improvement

#1193 Droth 1255 new form to add oth maintainers
  UI/newuser.html
  UI/src/less/core/forms.less
  digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
  digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/authentication/SessionApi.scala
  digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/user/UserConfigurationApi.scala
  digiroad2-api-common/src/test/scala/fi/liikennevirasto/digiroad2/user/UserConfigurationApiSpec.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/user/DummyUserProvider.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/user/User.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/user/UserProvider.scala
  digiroad2-oracle/sql/insert_users.sql
  digiroad2-oracle/src/main/resources/db/migration/V167__add_column_name_to_service_user.sql
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/MunicipalityService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/MunicipalityDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/OracleUserProvider.scala
  package.json
Labels: merge ready

#1196 Droth 1274 tool for selecting multiple links
  UI/src/application.js
  UI/src/assetTypeConfiguration.js
  UI/src/model/selectedLinearAsset.js
  UI/src/view/linear_asset/linearAssetLayer.js
  UI/src/view/linear_asset/manoeuvreLayer.js
  UI/src/view/linear_asset/speedLimitLayer.js
  UI/src/view/link_property/linkPropertyLayer.js
  UI/src/view/point_asset/groupedPointAssetLayer.js
  UI/src/view/point_asset/massTransitStopLayer.js
  UI/src/view/point_asset/pointAssetLayer.js
  UI/src/view/providers/selectToolControl.js
Labels: merge ready

#1208 DROTH-1356-After_Split_or_Separate_select_Linear_asset_doesnt_work_pr…
  UI/src/view/linear_asset/linearAssetLayer.js
Labels: bug
