Repository finnishtransportagency/digiroad2, pull requests merged in 2018-06, with the labels that each got.

#1212 DROTH-1357 && DROTH-1356 Multiple selection toll, split and separete do not work properly
  UI/src/application.js
  UI/src/model/selectedLinearAsset.js
  UI/src/view/linear_asset/linearAssetForm.js
  UI/src/view/linear_asset/linearAssetLayer.js
  UI/src/view/linear_asset/linearAssetMassUpdateDialog.js
  UI/src/view/providers/selectToolControl.js
Labels: merge ready

#1206 DROTH-26 Public transport lane to have period of validity to form and Kalpa-API
  UI/src/asset-type-layer-specifications.js
  UI/src/assetTypeConfiguration.js
  UI/src/less/site/linear-asset-form.less
  UI/src/model/selectedLinearAsset.js
  UI/src/model/selectedLinearAssetFactory.js
  UI/src/utils/date-utils.js
  UI/src/view/assetFormFactory.js
  UI/src/view/dynamicAssetForm.js
  UI/src/view/linear_asset/linearAssetLabel.js
  UI/src/view/linear_asset/linearAssetMassUpdateDialog.js
  UI/test/integration-tests.html
  UI/tmpl/index.html
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/asset/asset.scala
  digiroad2-oracle/src/main/resources/db/migration/V168__create_table_validity_period_value.sql
  digiroad2-oracle/src/main/resources/db/migration/V169__insert_property_for_mass_transit_lanes_dynamic_form.sql
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/MultiValueLinearAssetDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/queries.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/MultiValueLinearAssetService.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/dao/linearasset/MultiValueLinearAssetDaoSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/MultiValueLinearAssetServiceSpec.scala
Labels: merge ready

#1215 DROTH-1376 After saving links reports error
  UI/src/model/selectedLinearAsset.js
  UI/src/view/linear_asset/linearAssetLayer.js
Labels: bug

#1216 DROTH-1379 Slowness detected on multi Select
  UI/src/view/linear_asset/linearAssetLayer.js
  UI/src/view/linear_asset/linearAssetMassUpdateDialog.js
Labels: bug, merge ready

#1207 Droth 1350 european roads exit numbers mandatory field
  UI/src/model/selectedLinearAssetFactory.js
  UI/src/view/linear_asset/linearAssetForm.js
  UI/src/view/linear_asset/linearAssetLabel.js
  UI/src/view/linear_asset/piecewiseLinearAssetFormElements.js
  UI/src/view/linear_asset/piecewiseLinearAssetStyle.js
  UI/src/view/providers/assetStyle.js
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/LinearAssetService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/TextValueLinearAssetService.scala
Labels: merge ready

#1211 DROTH-1046 Remove Congestion tendency asset type form OTH
  UI/src/application.js
  UI/src/assetTypeConfiguration.js
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/asset/asset.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/CsvGenerator.scala
Labels: merge ready
