Repository finnishtransportagency/digiroad2, pull requests merged in 2019-04, with the labels that each got.

#1379 DROTH-1925_municipality_page_does_not_fit
  UI/src/view/municipalityWorkList.js
Labels: bug

#1376 DROTH-1917_additional_panel_batch_fix
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/CsvDataImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficSignService.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficSignServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
Labels: Improvement, bug

#1380 Droth-1838_search_tiekunta_bug_fixes
  UI/src/view/navigationpanel/searchBox.js
Labels: bug

#1378 DROTH-1918: road links for tierekisteri assets should be restricted to state roads
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/importer/CareClassTierekisteriImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/importer/TierekisteriImporterOperations.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/importer/TrafficSignTierekisteriImporter.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/TierekisteriImporterOperationsSpec.scala
Labels: Improvement

#1383 DROTH-1933_checkbox_missing_on_pedestriacrossing_box
  UI/src/application.js
Labels: bug

#1381 DROTH-1924_calendar_does_not_fit_form
  UI/src/less/site/pikaday-custom.less
Labels: bug

#1386 DROTH-1973_additional_panel_rename
  digiroad2-oracle/src/main/resources/db/migration/V197__rename_additional_panel.sql
Labels: bug

#1385 DROTH-1938_csv_importer_roadlink_selection_update
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/CsvDataImporter.scala
Labels: bug
