Repository finnishtransportagency/digiroad2, pull requests merged in 2019-11, with the labels that each got.

#1417 Droth 1926 Adding moving bus stops with CSV importer
  UI/src/csvImporter.js
  UI/src/less/core/tables.less
  UI/src/less/site/pages.less
  digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/dataimport/ImportDataApi.scala
  digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataimport/CsvDataImporterSpec.scala
  digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataimport/MassTransitStopCsvImporterSpec.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/asset/asset.scala
  digiroad2-oracle/src/main/resources/db/migration/V210__increase_filename_size_csv_import.sql
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/CsvDataImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/PointAssetOperations.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/MaintenanceRoadCsvImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/MassTransitStopCsvImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/ObstaclesCsvImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/PedestrianCrossingCsvImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/PointAssetCsvImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/RailwayCrossingCsvImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/RoadLinkCsvImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/ServicePointCsvImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/TrafficLightsCsvImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/TrafficSignCsvImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/DynamicLinearAssetDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/ImportLogDAO.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/MassTransitStopDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/middleware/DataImportManager.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/MassTransitStopService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/MassTransitStopExcelDataImporter.scala
  src/main/scala/ScalatraBootstrap.scala
Labels: merge ready

#1421 DROTH-2092 Create Batch to get Wrong functional classes on the roads
  ci/pipeline/dev_task_runner
  ci/pipeline/prod_task_runner
  ci/pipeline/qa_task_runner
  ci/pipeline/staging_task_runner
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/RoadLinkDAO.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
Labels: merge ready

#1428 Droth 2101 new field for bus stops
  UI/src/view/point_asset/massTransitStopForm.js
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
  digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/Digiroad2ApiSpec.scala
  digiroad2-oracle/src/main/resources/db/migration/V211__add_new_property_for_bus_stops.sql
Labels: Flyway Version, merge ready

#1423 Droth 2013 adding liikvast info
  UI/src/view/point_asset/trafficSignForm.js
  digiroad2-oracle/src/main/resources/db/migration/V212__add_new_road_sign_side_column.sql
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/TierekisteriTrafficSignAssetClient.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/importer/TrafficSignTierekisteriImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OracleTrafficSignDao.scala
Labels: Flyway Version, merge ready

#1439 DROTH-2171 Double checkmark on checked asset:
  UI/src/application.js
  UI/src/authorizationpolicies/authorizationPolicy.js
  UI/src/view/linear_asset/speedLimitForm.js
  UI/src/view/municipalityWorkList.js
  UI/src/view/navigationpanel/actionPanelBox.js
Labels: bug

#1440 DROTH-1467_Wrong_functional_class_on_road_link
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/vvh/VVHClient.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
Labels: bug, merge ready

#1442 Droth 2116 update method for the new municipality api
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/MunicipalityApi.scala
  digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/MunicipalityApiSpec.scala
  digiroad2-oracle/src/main/resources/db/migration/V213__add_table_dataset.sql
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/AwsDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/MunicipalityDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OracleObstacleDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/ObstacleService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/PavedRoadService.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitServiceSpec.scala
  src/main/scala/ScalatraBootstrap.scala
Labels: Flyway Version, urgent

#1444 DROTH-2185 Remove the checkbox "Näytä maastossa kuvatut liikennemerkit"
  UI/src/application.js
  UI/src/view/point_asset/trafficSignToggle.js
  UI/src/view/vioniceLayer.js
  UI/test/integration-tests.html
  UI/tmpl/index.html
Labels: bug
