Repository finnishtransportagency/digiroad2, pull requests merged in 2019-12, with the labels that each got.

#1448 Droth 2199 accept other characters as feature
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/MunicipalityApi.scala
  digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/MunicipalityApiSpec.scala
  digiroad2-oracle/src/main/resources/db/migration/V214__alter_municipality_feature_id_column.sql
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/AwsDao.scala
Labels: Flyway Version, bug

#1446 DROTH-2198_crs_optional_in_update
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/MunicipalityApi.scala
  digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/MunicipalityApiRequestSpec.scala
  digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/MunicipalityApiSpec.scala
Labels: bug

#1447 DROTH-2201 error in console on login
  UI/src/router.js
  UI/src/utils/backend-utils.js
  UI/src/utils/data-import-backend.js
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
Labels: bug

#1453 DROTH-2232 Traffic Sign doesnt allow update
  UI/src/view/point_asset/trafficSignForm.js
Labels: bug

#1452 DROTH-2216 Obstacle batch
  ci/pipeline/dev_task_runner
  ci/pipeline/prod_task_runner
  ci/pipeline/qa_task_runner
  ci/pipeline/staging_task_runner
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OracleObstacleDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/ObstacleService.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
Labels: urgent
