Repository finnishtransportagency/digiroad2, pull requests merged in 2019-02, with the labels that each got.

#1340 DROTH-1799: changes in user info logs
  UI/src/authorizationpolicies/authorizationPolicy.js
  UI/src/authorizationpolicies/linkPropertyAuthorizationPolicy.js
  UI/src/view/dynamicAssetForm.js
  UI/src/view/feedbackApplicationTool.js
  UI/src/view/feedbackDataTool.js
  UI/src/view/linear_asset/linearAssetForm.js
  UI/src/view/linear_asset/manoeuvreForm.js
  UI/src/view/linear_asset/speedLimitForm.js
  UI/src/view/link_property/linkPropertyForm.js
  UI/src/view/point_asset/massTransitStopForm.js
  UI/src/view/point_asset/pointAssetForm.js
  UI/test/integration-tests.html
  UI/tmpl/index.html
Labels: bug

#1344 Droth 1821 dashboard close button reach
  UI/src/view/municipalitySituationPopup.js
  UI/src/view/userNotificationPopup.js
Labels: bug

#1346 DROTH-1839 quality error list rename and link modification
  UI/src/view/dynamicAssetForm.js
  UI/src/view/linear_asset/linearAssetForm.js
  UI/src/view/linear_asset/manoeuvreForm.js
  UI/src/view/linear_asset/speedLimitForm.js
  UI/src/view/point_asset/pointAssetForm.js
  UI/src/view/workListView.js
Labels: bug

#1349 DROTH-1845 improved link matching
  UI/src/view/linear_asset/linearAssetLayer.js
Labels: bug

#1356 DROTH-1846 Text for the user rights
  UI/src/view/linear_asset/speedLimitForm.js
Labels: bug, merge ready

#1347 DROTH-1831 Split assets position adjustment
  UI/src/model/selectedLinearAsset.js
  UI/src/view/linear_asset/linearAssetLayer.js
Labels: bug

#1355 DROTH-1861_carrying_capacity_save_condition
  UI/src/assetTypeConfiguration.js
Labels: bug, merge ready

#1358 DROTH-1864 Asset menu order
  UI/src/application.js
Labels: bug

#1341 DROTH-1755 Change http.nonProxyHosts to work with vayla.fi-domain
  conf/dev/digiroad2.properties
  gruntfile.js
  src/main/scala/fi/liikennevirasto/digiroad2/DigiroadServer.scala
Labels: merge ready

#1350 DROTH-1784: side code added to mass transit lane importer
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/TierekisteriMassTransitLaneAssetClient.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/importer/MassTransitLaneTierekisteriImporter.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/TierekisteriImporterOperationsSpec.scala
Labels: Improvement

#1351 DROTH_vii_te_component_removal
  digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
  digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/Digiroad2ApiSpec.scala
  digiroad2-api-viite/src/main/scala/fi/liikennevirasto/digiroad2/ViiteApi.scala
  digiroad2-api-viite/src/test/scala/fi/liikennevirasto/digiroad2/ViiteIntegrationApiSpec.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/importer/TierekisteriImporterOperations.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/RoadAddressDAO.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadAddressService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/BusStopStrategy.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/GeometryTransform.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/TierekisteriDataImporter.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/MassTransitStopServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/GeometryTransformSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/TierekisteriImporterOperationsSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/TierekisteriPointConversionImporterSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceLinkSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/RoadAddressServiceSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/dao/CalibrationPointDAOSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/AssetDataImporterSpec.scala
  digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/ProjectLinkSplitterSpec.scala
  src/main/scala/fi/liikennevirasto/digiroad2/ViiteTestServer.scala
  src/main/webapp/WEB-INF/viite_web.xml
  viite-fixture-reset.sh
  viitepackage.json
Labels: Improvement

#1329 Droth 1735 modify boggie weight limit validator handle with additional info
  UI/src/assetTypeConfiguration.js
  UI/src/view/dynamicAssetForm.js
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/process/BogieWeightLimitValidator.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/DynamicLinearAssetService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/LinearAssetService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/LinearBogieWeightLimitService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/PavedRoadService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/AssetValidatorProcess.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/SevenRestrictionsLimitationValidatorSpec.scala
Labels: Only can be deployed after DROTH-1707 / 1693

#1345 DROTH-1791_csv_importer_improvement
  UI/csv_import.html
  UI/excel_import.html
  UI/images/crossingSign.png
  UI/images/csv-status-icons/check-icon.png
  UI/images/csv-status-icons/clock-outline.png
  UI/images/csv-status-icons/error-icon-small.png
  UI/images/csv-status-icons/not-ok-check-icon.png
  UI/images/csv-status-icons/unknown-error.png
  UI/images/oldAsset.png
  UI/images/speedLimitSign.png
  UI/images/turningSign.png
  UI/images/warningSign.png
  UI/src/csvImporter.js
  UI/src/less/core/tables.less
  UI/src/less/site/content-box.less
  UI/src/utils/data-import-backend.js
  UI/src/view/municipalityWorkList.js
  digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/dataimport/CsvDataImporter.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/dataimport/CsvImporter.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/dataimport/ImportDataApi.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/dataimport/MassTransitStopImportApi.scala
  digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataimport/CsvDataImporterSpec.scala
  digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataimport/CsvImporterSpec.scala
  digiroad2-oracle/src/main/resources/db/migration/V195__add_new_column_to_import_log_table.sql
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/CsvDataImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/importer/TrafficSignTierekisteriImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/ImportLogDAO.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/middleware/DataImportManager.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/oracle/ImportLogService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/process/AssetValidator.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficSignService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/AssetValidatorProcess.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/RoundaboutProcessor.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/SpeedLimitValidatorSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/RoadLinkServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/ManoeuvreServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/ProhibitionServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficSignServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
  src/main/scala/ScalatraBootstrap.scala
Labels: Flyway Version
