Repository finnishtransportagency/digiroad2, pull requests merged in 2019-07, with the labels that each got.

#1412 Droth 2038 additional panel exception missing creating linear
  UI/images/traffic-signs/additional-panels/HusvagnCaravan.png
  UI/images/traffic-signs/additional-panels/Moped.png
  UI/images/traffic-signs/additional-panels/drivingInServicePurposesAllowed.png
  UI/src/controller/trafficSignsCollection.js
  UI/src/controller/trafficSignsReadOnlyCollection.js
  UI/src/view/point_asset/trafficSignLabel.js
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/TrafficSign.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/asset/asset.scala
  digiroad2-oracle/src/main/resources/db/migration/V205___add_more_new_traffic_sign_enumerated_value.sql
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/TrafficSignLinearGenerator.scala
Labels: Flyway Version, merge ready

#1414 Droth 2057 adding private road association names
  digiroad2-oracle/src/main/resources/db/migration/V206___add_road_attributes_constrains.sql
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/RoadLinkDAO.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/RoadLinkServiceDAO.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/queries.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
Labels: Flyway Version, need changes

#1387 Droth 1860 publishing xml for bus stop change info
  digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
  digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/util/AssetPropertiesReader.scala
  digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/vallu/ValluStoreStopChangeMessage.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/ChangeApi.scala
  digiroad2-oracle/src/main/resources/db/migration/V207__create_table_Vallu_XML_Ids.sql
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/MunicipalityService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/MassTransitStopDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/MassTransitStopService.scala
  gruntfile.js
Labels: Flyway Version

#1410 Droth 1931 timestamp for private road information
  UI/src/less/core/forms.less
  UI/src/view/link_property/linkPropertyForm.js
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/RoadLinkDAO.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
Labels: need changes

#1400 Droth 1754 parking prohibition v2
  UI/src/application.js
  UI/src/assetTypeConfiguration.js
  UI/src/controller/trafficSignsCollection.js
  UI/src/controller/trafficSignsReadOnlyCollection.js
  UI/src/less/core/variables.less
  UI/src/less/site/action-panel.less
  UI/src/less/site/linear-asset-form.less
  UI/src/model/selectedLinearAssetFactory.js
  UI/src/router.js
  UI/src/view/autoGeneratedAssetsWorkList.js
  UI/src/view/linear_asset/parkingProhibitionStyle.js
  UI/src/view/navigationpanel/parkingProhibitionBox.js
  UI/test/integration-tests.html
  UI/tmpl/index.html
  digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/TrafficSign.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/asset/asset.scala
  digiroad2-oracle/src/main/resources/db/migration/V208__create_new_parking_asset.sql
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/OracleLinearAssetDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/middleware/TrafficSignManager.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/DynamicLinearAssetService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/HazmatTransportProhibitionService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/LinearAssetService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/ParkingProhibitionService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/PavedRoadService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/TrafficSignLinearGenerator.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/TrafficSignLinearGeneratorSpec.scala
Labels: Flyway Version

#1393 Droth 1936 information signs to traffic signs
  UI/images/traffic-signs/information-signs/AdvanceDirectionSign.png
  UI/images/traffic-signs/information-signs/AdvanceDirectionSignAbove.png
  UI/images/traffic-signs/information-signs/AdvanceDirectionSignAboveSmall.png
  UI/images/traffic-signs/information-signs/AdvanceDirectionSignSmall.png
  UI/images/traffic-signs/information-signs/AdvisorySignDetour.png
  UI/images/traffic-signs/information-signs/AdvisorySignDetourLarge.png
  UI/images/traffic-signs/information-signs/Airport.png
  UI/images/traffic-signs/information-signs/BiDirectionalInformationOnTrafficLanes.png
  UI/images/traffic-signs/information-signs/BusStation.png
  UI/images/traffic-signs/information-signs/Detour.png
  UI/images/traffic-signs/information-signs/DirectionSign.png
  UI/images/traffic-signs/information-signs/DirectionSignForDetour.png
  UI/images/traffic-signs/information-signs/DirectionSignForDetourWithText.png
  UI/images/traffic-signs/information-signs/DirectionSignForLightTraffic.png
  UI/images/traffic-signs/information-signs/DirectionSignForLocalPurposes.png
  UI/images/traffic-signs/information-signs/DirectionSignForMotorway.png
  UI/images/traffic-signs/information-signs/DirectionSignOnPrivateRoad.png
  UI/images/traffic-signs/information-signs/DirectionToEmergencyExit.png
  UI/images/traffic-signs/information-signs/DirectionToTheNumberedRoad.png
  UI/images/traffic-signs/information-signs/EmergencyExit.png
  UI/images/traffic-signs/information-signs/EndOfLane.png
  UI/images/traffic-signs/information-signs/ExitSign.png
  UI/images/traffic-signs/information-signs/ExitSignAbove.png
  UI/images/traffic-signs/information-signs/Ferry.png
  UI/images/traffic-signs/information-signs/GoodsHarbour.png
  UI/images/traffic-signs/information-signs/IndustrialArea.png
  UI/images/traffic-signs/information-signs/InformationOnTrafficLanes.png
  UI/images/traffic-signs/information-signs/ItineraryForDangerousGoodsTransport.png
  UI/images/traffic-signs/information-signs/LocationSign.png
  UI/images/traffic-signs/information-signs/OverpassOrUnderpassWithSteps.png
  UI/images/traffic-signs/information-signs/OverpassOrUnderpassWithoutSteps.png
  UI/images/traffic-signs/information-signs/ParkAndRideFacilities.png
  UI/images/traffic-signs/information-signs/PlaceName.png
  UI/images/traffic-signs/information-signs/RailwayStation.png
  UI/images/traffic-signs/information-signs/RecommendedMaxSpeed.png
  UI/images/traffic-signs/information-signs/RoadForMotorVehicles.png
  UI/images/traffic-signs/information-signs/RoadNumberERoad.png
  UI/images/traffic-signs/information-signs/RoadNumberOrdinaryRoad.png
  UI/images/traffic-signs/information-signs/RoadNumberPrimaryRoad.png
  UI/images/traffic-signs/information-signs/RoadNumberRegionalOrSecondaryRoad.png
  UI/images/traffic-signs/information-signs/RouteToBeFollowed.png
  UI/images/traffic-signs/information-signs/SignShowingDistance.png
  UI/src/controller/trafficSignsCollection.js
  UI/src/view/point_asset/signsLabel.js
  UI/src/view/point_asset/trafficSignLabel.js
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/TrafficSign.scala
  digiroad2-oracle/src/main/resources/db/migration/V208__information_signs_to_enumerated_values.sql
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/importer/TrafficSignTierekisteriImporter.scala
Labels: Flyway Version
