Repository finnishtransportagency/digiroad2, pull requests merged in 2019-01, with the labels that each got.

#1325 Ol5 deploy tasks removed
  UI/components/ol-dist/ol.css
  UI/components/ol-dist/ol.js
  UI/src/application.js
  UI/src/assetTypeConfiguration.js
  UI/src/view/linear_asset/carryingCapacityStyle.js
  UI/src/view/linear_asset/linearAssetLabel.js
  UI/src/view/linear_asset/winterSpeedLimitStyle.js
  UI/src/view/point_asset/massTransitMarker.js
  UI/src/view/providers/selectToolControl.js
  UI/test/integration-tests.html
  UI/tmpl/index.html
  gruntfile.js
  package.json
Labels: Do not merge

#1313 Droth 1664 linking additional signs v2
  UI/src/assetTypeConfiguration.js
  UI/src/less/core/forms.less
  UI/src/less/site/asset-form.less
  UI/src/model/selectedPointAsset.js
  UI/src/view/point_asset/pointAssetForm.js
  UI/src/view/point_asset/trafficSignForm.js
  UI/src/view/point_asset/trafficSignLabel.js
  digiroad2-api-oth/src/main/resources/logback.xml
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/ChangeApi.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/asset/asset.scala
  digiroad2-oracle/src/main/resources/db/migration/V191__new_additional_panel_table_and_properties.sql
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/importer/TrafficSignTierekisteriImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OracleTrafficSignDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/queries.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/process/AssetValidator.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/process/AxleWeightLimitValidator.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/process/BogieWeightLimitValidator.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/process/HazmatTransportProhibitionValidator.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/process/HeightLimitValidator.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/process/LengthLimitValidator.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/process/ManoeuvreValidator.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/process/PedestrianCrossingValidator.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/process/SevenRestrictionsLimitationValidator.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/process/SpeedLimitValidator.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/process/TotalWeightLimitValidator.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/process/TrailerTruckWeightLimitValidator.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/process/WidthLimitValidator.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/ManoeuvreService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficSignService.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/HazmatTransportProhibitionValidatorSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/ManoeuvreValidatorSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/PedestrianCrossingValidatorSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/SevenRestrictionsLimitationValidatorSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/SpeedLimitValidatorSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/ManoeuvreServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficSignServiceSpec.scala
Labels: merge ready

#1326 DROTH-1745 UI: separation causes duplicate features
  UI/src/less/site/linear-asset-form.less
  UI/src/model/selectedLinearAsset.js
  UI/src/model/selectedLinearAssetFactory.js
  UI/src/view/linear_asset/linearAssetLayer.js
Labels: bug, merge ready

#1327 DROTH-1752 fixed regex matching for exit numbers
  UI/src/model/selectedLinearAssetFactory.js
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/TextValueLinearAssetService.scala
Labels: bug, merge ready

#1322 DROTH-1686 TierekisteriImporter: create method to handle irregular va…
  UI/src/assetTypeConfiguration.js
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/importer/TrafficSignTierekisteriImporter.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/TierekisteriImporterOperationsSpec.scala
Labels: merge ready

#1321 Droth 1725 combining linears
  digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/MunicipalityApi.scala
  digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/Digiroad2ApiSpec.scala
  digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/MunicipalityApiSpec.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/AssetFiller.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/OneWayAssetFiller.scala
  digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/linearasset/AssetFillerSpec.scala
  digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/linearasset/OneWayAssetFillerSpec.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/LinearAssetService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/MaintenanceService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/MassTransitLaneService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/NumberOfLanesService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/ProhibitionService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/RoadWidthService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/PavedRoadService.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/DynamicLinearAssetServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/LinearAssetServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/MassTransitLaneServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/NumberOfLanesServiceSpec.scala
  src/main/scala/ScalatraBootstrap.scala
Labels: merge ready

#1333 DROTH-1756: domain name change
  conf/production/digiroad2.properties
  conf/production2/digiroad2.properties
  conf/staging/digiroad2.properties
  conf/testing/digiroad2.properties
  conf/testing2/digiroad2.properties
Labels: bug

#1335 DROTH-1783_experimental_zoom_lvl_fix
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/OracleLinearAssetDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/LinearAssetService.scala
Labels: bug

#1319 Droth 1693 tr height weight and bogie
  UI/src/assetTypeConfiguration.js
  UI/src/model/selectedLinearAssetFactory.js
  UI/src/view/dynamicAssetForm.js
  digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/ChangeApi.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
  digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/Digiroad2ApiSpec.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/LinearAsset.scala
  digiroad2-oracle/src/main/resources/db/migration/V192_1__add_new_bogie_weight_properties.sql
  digiroad2-oracle/src/main/resources/db/migration/V192_2__update_property_id_of_existing_bogie_weights.sql
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/LinearMassLimitationService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/TierekisteriWeightLimitAssetClient.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/importer/TierekisteriPointConversionImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/vvh/VVHClient.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/DynamicLinearAssetDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/DynamicLinearAssetService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/LinearBogieWeightLimitService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/TierekisteriDataImporter.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/LinearMassLimitationServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/TierekisteriPointConversionImporterSpec.scala
Labels: Flyway Version, merge ready

#1323 Droth 1724 ui improvements v2
  UI/src/application.js
  UI/src/assetTypeConfiguration.js
  UI/src/less/site/action-panel.less
  UI/src/less/site/asset-form.less
  UI/src/less/site/global.less
  UI/src/less/site/modals.less
  UI/src/view/assetSelectionMenu.js
  UI/src/view/dynamicAssetForm.js
  UI/src/view/feedbackApplicationTool.js
  UI/src/view/feedbackDataTool.js
  UI/src/view/linear_asset/linearAssetForm.js
  UI/src/view/linear_asset/manoeuvreForm.js
  UI/src/view/linear_asset/speedLimitForm.js
  UI/src/view/link_property/linkPropertyForm.js
  UI/src/view/point_asset/massTransitStopForm.js
  UI/src/view/point_asset/pointAssetForm.js
  UI/src/view/workListView.js
  UI/test/test-runner.html
  UI/tmpl/index.html
Labels: Changes After Code Review, merge ready

#1336 DROTH-1722 Functional class change from vvh update
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/vvh/VVHClient.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
Labels: bug, merge ready

#1339 DROTH-1786 Create Hazmat Prohibition with duplicate VAK property sepa…
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/LinearAsset.scala
Labels: bug, merge ready
