Repository finnishtransportagency/digiroad2, pull requests merged in 2020-08, with the labels that each got.

#1556 DROTH-2488 Lane cut won't save properly
  UI/src/model/selectedLaneModelling.js
  UI/src/utils/laneUtils.js
Labels: bug, merge ready

#1559 DROTH-2490 (US 2464) Removed deprecated viite server handler
  src/main/scala/fi/liikennevirasto/digiroad2/DigiroadServer.scala
Labels: merge ready

#1560 DROTH-2505 Municipality page for Akaa does not load
  UI/src/view/municipalityWorkList.js
Labels: bug, merge ready

#1555 Droth 2266 add lane information to change api for tr v2
  UI/src/model/selectedLaneModelling.js
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/ChangeApi.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/Lane.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/LaneFiller.scala
  digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/lane/LaneFillerSpec.scala
  digiroad2-oracle/src/main/resources/db/migration/V232__create_history_lane_tabels.sql
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/lane/LaneDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/lane/LaneHistoryDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/LaneUtils.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/lane/LaneServiceSpec.scala
Labels: Flyway Version, Second to Deploy, merge ready

#1562 DROTH-2473 Work list problems
  UI/src/assetTypeConfiguration.js
  UI/src/view/dynamicAssetForm.js
  UI/src/view/workListView.js
Labels: bug, merge ready

#1563 DROTH-2068 Rendered text in traffic signs visible through overlapping…
  UI/src/view/point_asset/signsLabel.js
  UI/src/view/point_asset/trafficSignLabel.js
Labels: bug

#1557 Droth 2465 lane tool improvements part 2
  UI/src/application.js
  UI/src/assetTypeConfiguration.js
  UI/src/controller/laneModellingCollection.js
  UI/src/controller/linearAssetsCollection.js
  UI/src/model/selectedLaneModelling.js
  UI/src/utils/backend-utils.js
  UI/src/utils/laneUtils.js
  UI/src/utils/property-utils.js
  UI/src/view/linear_asset/laneModellingForm.js
  UI/src/view/linear_asset/laneModellingLayer.js
  UI/src/view/linear_asset/laneModellingStyle.js
  UI/src/view/linear_asset/linearAssetLayer.js
  UI/src/view/linear_asset/viewOnlyLaneModellingLayer.js
  UI/src/view/navigationpanel/actionPanelBox.js
  UI/src/view/navigationpanel/linearAssetBox.js
  UI/src/view/providers/selectToolControl.js
  UI/test/integration-tests.html
  UI/tmpl/index.html
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/asset/asset.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/Lane.scala
  digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/linearasset/AssetFillerSpec.scala
  digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/linearasset/SpeedLimitFillerSpec.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/LaneUtils.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/RoadLinkServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/lane/LaneServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/DirectionalTrafficSignServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/HeightLimitServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/ObstacleServiceSpec.scala
Labels: Third to Deploy, merge ready

#1564 DROTH-2508 Restore expired assets in Ahvenanmaa
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/asset/asset.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/importer/TierekisteriImporterOperations.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/importer/TrafficSignTierekisteriImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/OracleAssetDao.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
Labels: Batch to Run, merge ready

#1565 DROTH-2507 Problem when extracting obstacles
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/PointAssetOperations.scala
Labels: bug

#1558 Droth 2454 reports from municipality page
  UI/src/application.js
  UI/src/less/core/forms.less
  UI/src/less/site/global.less
  UI/src/less/site/pages.less
  UI/src/router.js
  UI/src/utils/backend-utils.js
  UI/src/view/csvReportsWorkList.js
  UI/src/view/municipalityWorkList.js
  UI/test/integration-tests.html
  UI/tmpl/index.html
  digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/dataexport/ExportDataApi.scala
  digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataexport/AssetReportCsvExporterSpec.scala
  digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataexport/CsvDataExporterSpec.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/asset/asset.scala
  digiroad2-oracle/src/main/resources/db/migration/V232__add_export_report_table.sql
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/CsvDataExporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/MunicipalityService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataExporter/AssetReportCsvExporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/ExportReportDAO.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/MunicipalityDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/csvexporter/AssetReporterDAO.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/middleware/DataExportManager.scala
  src/main/scala/ScalatraBootstrap.scala
Labels: Flyway Version, merge ready

#1567 Droth 2511 and Droth 2512
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/TrafficSign.scala
  digiroad2-oracle/src/main/resources/db/migration/V234__remove_unnecessary_traffic_signs_and_name_updates.sql
Labels: Flyway Version, merge ready

#1568 DROTH-2513 Minimum speed limit value must be mandatory
  UI/src/assetTypeConfiguration.js
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/TrafficSign.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/TrafficSignCsvImporter.scala
Labels: merge ready

#1571 Droth-2519 Color codes to traffic lights
  UI/src/assetTypeConfiguration.js
  UI/src/resources/digiroad2/bundle/assetlayer/images/direction-arrow-for-multiple.svg
  UI/src/resources/digiroad2/bundle/assetlayer/images/no-direction-for-multiple.svg
  UI/src/view/point_asset/pointAssetStyle.js
Labels: merge ready

#1576 DROTH-2526 Change api for lanes returning error
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/ChangeApi.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
Labels: bug, merge ready

#1573 DROTH-2521 Report lists changes in roads which it should not
  digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataexport/AssetReportCsvExporterSpec.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataExporter/AssetReportCsvExporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/csvexporter/AssetReporterDAO.scala
Labels: merge ready

#1575 DROTH-2524 Additional signs with time range
  UI/src/assetTypeConfiguration.js
  UI/src/view/point_asset/trafficSignLabel.js
Labels: bug, merge ready

#1572 Droth 2516 move old expired assets to another table
  digiroad2-oracle/src/main/resources/db/migration/V235__create_history_asset_tables.sql
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/HistoryDAO.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/HistoryService.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/HistoryServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
Labels: Flyway Version, merge ready
