Repository finnishtransportagency/digiroad2, pull requests merged in 2020-09, with the labels that each got.

#1577 DROTH-2520 (US 2454) Report from municipality page doesn't show newly…
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataExporter/AssetReportCsvExporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/csvexporter/AssetReporterDAO.scala
Labels: merge ready

#1578 Droth 2527 prohibitions generated by traffic signs created without time validations
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/TrafficSignLinearGenerator.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/TrafficSignLinearGeneratorSpec.scala
Labels: bug

#1579 DROTH-2529 (U.S:2454) Extraction board the button to show log info doesnt work in case of error
  UI/src/utils/backend-utils.js
  UI/src/view/csvReportsWorkList.js
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/dataexport/ExportDataApi.scala
  digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataexport/AssetReportCsvExporterSpec.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/CsvDataExporter.scala
Labels: bug, merge ready

#1582 DROTH-2534 Traffic sign csv-import
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/TrafficSignCsvImporter.scala
Labels: merge ready

#1584 Droth 2561 modify lane import to include additional lanes
  UI/src/csvImporter.js
  digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataimport/CsvDataImporterSpec.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/Lane.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/LanesCsvImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/lane/LaneDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
Labels: merge ready

#1585 DROTH-2563 Green color option for additional plates
  UI/src/view/point_asset/trafficSignForm.js
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/asset/asset.scala
Labels: merge ready

#1586 Droth 2564 problem with traffic lights extraction
  RobotProjectTest/Test/TestSuite/PedestrianCrossingTests.robot
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OracleTrafficLightDao.scala
Labels: merge ready

#1589 DROTH-2422 Wrong values on traffic signs
  UI/src/view/point_asset/pointAssetForm.js
Labels: merge ready
