Repository finnishtransportagency/digiroad2, pull requests merged in 2020-02, with the labels that each got.

#1455 Droth 2212 municipality merger
  ci/pipeline/dev_task_runner
  ci/pipeline/prod_task_runner
  ci/pipeline/qa_task_runner
  ci/pipeline/staging_task_runner
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/queries.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
Labels: urgent

#1465 DROTH-2281 Save button doesn't work on roadworks area selection
  UI/src/model/selectedLinearAssetFactory.js
  UI/src/view/dynamicAssetForm.js
  UI/src/view/linear_asset/linearAssetMassUpdateDialog.js
Labels: bug

#1464 Droth 1998 lorry parking datex transformation
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/asset/asset.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/queries.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/Datex2Generator.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
Labels: merge ready

#1466 DROTH-2279 (US 2014) Default asset type not working
  UI/src/application.js
  UI/src/less/site/modals.less
  UI/src/utils/backend-utils.js
  UI/src/view/defaultLocationButton.js
  UI/src/view/initialPopupView.js
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
  digiroad2-oracle/sql/insert_users.sql
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/MunicipalityService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/MunicipalityDao.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
Labels: bug, merge ready, urgent

#1469 DROTH-2273 (US 1891) Suggested assets-button is missing in municipali…
  UI/src/view/suggestedAssetsWorkList.js
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/VerificationDao.scala
Labels: bug

#1470 DROTH-2273 (US 1891) Suggested assets-button is missing in municipali…
  UI/src/router.js
  UI/src/view/speedLimitWorkList.js
  UI/src/view/workListView.js
Labels: bug

#1471 Droth 2285 private road information disappears when geometry changes
  digiroad2-oracle/src/main/resources/db/migration/V217__add_new_column_road_link_attributes_table.sql
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/RoadLinkDAO.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/RoadLinkServiceSpec.scala
Labels: Flyway Version, bug, urgent

#1463 DROTH-2243 Asset deletes when geometry updates
  digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/linearasset/SpeedLimitFillerSpec.scala
  digiroad2-oracle/sql/kauniainen_production_speed_limits.sql
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/OracleLinearAssetDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/OracleSpeedLimitDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/queries.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/LinearAssetService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/MaintenanceService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/ProhibitionService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/RoadWidthService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/PavedRoadService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/LinearAssetUtils.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/dao/linearasset/OracleSpeedLimitDaoSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/DynamicLinearAssetServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/LinearAssetServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/MassTransitLaneServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/NumberOfLanesServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/ProhibitionServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/RoadWidthServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/TextValueLinearAssetServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/PavedRoadServiceSpec.scala
Labels: urgent

#1430 DROTH-2096_new_liikvast_field
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/TierekisteriTrafficSignAssetClient.scala
Labels: Flyway Version, merge ready

#1431 Droth 2059 indicate conflicting field values within road link chain
  UI/src/model/selectedLinkProperty.js
  UI/src/view/link_property/linkPropertyForm.js
Labels: merge ready

#1432 Droth 2098 unknown speed limit list upgrade part 2
  UI/src/less/core/tables.less
  UI/src/utils/backend-utils.js
  UI/src/view/workListView.js
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
  digiroad2-oracle/src/main/resources/db/migration/V218__add_new_column_unknown_speed_limit_table.sql
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/OracleSpeedLimitDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitService.scala
Labels: Flyway Version, merge ready

#1443 DROTH-2189 fixes on newuser page
  UI/newuser.html
Labels: bug

#1474 DROTH-2305 Private road information disappears from some links
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/RoadLinkServiceSpec.scala
Labels: bug, urgent
