Repository finnishtransportagency/digiroad2, pull requests merged in 2020-03, with the labels that each got.

#1476 Droth 2306 some bugs in unknown speed limit list
  digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
  digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/SpeedLimitUpdaterSpec.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/RoadLink.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitService.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
Labels: bug

#1477 DROTH-2309 (US 2059) Address numbers don't show as they should
  UI/src/model/selectedLinkProperty.js
  UI/src/view/link_property/linkPropertyForm.js
Labels: bug

#1478 DROTH-2311 (US 2143) Calls about the new VKM are returning a 404 error
  conf/dev/keys.properties
  src/main/scala/fi/liikennevirasto/digiroad2/DigiroadServer.scala
Labels: bug, merge ready

#1479 Droth 2307 oth crashes on production servers
  ci/pipeline/dev_task_runner
  ci/pipeline/prod_task_runner
  ci/pipeline/qa_task_runner
  ci/pipeline/staging_task_runner
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/OracleSpeedLimitDao.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
Labels: Batch to Run, bug, urgent

#1482 DROTH-2268 Bus stops that need to be deleted
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/TerminatedBusStopStrategy.scala
Labels: urgent

#1481 DROTH-2307 OTH crashes on both production servers
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitService.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
Labels: Batch to Run, bug, urgent

#1473 Droth 2046 situation pop up information
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
  digiroad2-oracle/src/main/resources/db/migration/V219__create_new_dashboard_table.sql
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/VerificationDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/VerificationService.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/VerificationServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
Labels: Batch to Run, First to Deploy, Flyway Version, Old User Story, merge ready

#1472 Droth 2142 culverts for service points
  UI/images/service_points/culvert.png
  UI/src/assetTypeConfiguration.js
  UI/src/less/core/forms.less
  UI/src/less/site/action-panel.less
  UI/src/utils/backend-utils.js
  UI/src/view/point_asset/massTransitStopForm.js
  UI/src/view/point_asset/pointAssetForm.js
  UI/src/view/point_asset/servicePointForm.js
  UI/src/view/point_asset/servicePointLabel.js
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/asset/asset.scala
  digiroad2-oracle/src/main/resources/db/migration/V220__add_new_column_service_point_value_table.sql
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/ServicePointCsvImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OracleServicePointDao.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/ServicePointServiceSpec.scala
Labels: Flyway Version, Old User Story, Second to Deploy, merge ready

#1457 Droth 2190 cycling and walking asset
  UI/src/application.js
  UI/src/assetTypeConfiguration.js
  UI/src/authorizationpolicies/cyclingAndWalkingAuthorizationPolicy.js
  UI/src/controller/trafficSignsReadOnlyCollection.js
  UI/src/less/core/variables.less
  UI/src/less/site/action-panel.less
  UI/src/model/selectedLinearAssetFactory.js
  UI/src/router.js
  UI/src/view/dynamicAssetForm.js
  UI/src/view/linear_asset/cyclingAndWalkingStyle.js
  UI/src/view/navigationpanel/cyclingAndWalkingBox.js
  UI/src/view/point_asset/trafficSignReadOnlyLayer.js
  UI/test/integration-tests.html
  UI/tmpl/index.html
  ci/pipeline/dev_task_runner
  ci/pipeline/prod_task_runner
  ci/pipeline/qa_task_runner
  ci/pipeline/staging_task_runner
  digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/asset/asset.scala
  digiroad2-oracle/src/main/resources/db/migration/V221__cycling_and_walking_asset.sql
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/ImportShapeFileDAO.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OracleObstacleDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/queries.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/CyclingAndWalkingService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/DynamicLinearAssetService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/LinearAssetService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/TextValueLinearAssetService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/ObstacleService.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
Labels: Batch to Run, Flyway Version, Third to Deploy, merge ready

#1487 DROTH-2333 Kalpa api returning paved_roads type code in a list
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
Labels: bug

#1488 DROTH-2334 KalpaApi_returning_500_error_for_certain_asset_types
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OracleObstacleDao.scala
Labels: bug

#1485 DROTH-2329 create_prohibition_using_traffic_signs batch not working
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/OracleLinearAssetDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OracleTrafficSignDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficSignService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/TrafficSignLinearGenerator.scala
Labels: bug

#1489 DROTH-2331 Speed limit search not working
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/RoadLink.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/OracleSpeedLimitDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/SpeedLimitService.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
Labels: bug, urgent

#1490 Droth 2335 extraction railway and pedestrian crossing fails
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OracleDirectionalTrafficSignDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OracleObstacleDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OraclePedestrianCrossingDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OracleRailwayCrossingDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OracleServicePointDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OracleTrafficLightDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OracleTrafficSignDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OracleTrailerTruckWeightLimitDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OracleWidthLimitDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/PropertyValidator.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/RoadLinkServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/UserNotificationServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/PedestrianCrossingServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/RailwayCrossingServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficLightServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/WeightLimitServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/WidthLimitServiceSpec.scala
Labels: bug, urgent

#1491 Droth 2326 batch resolve frozen links doesnt run with this vkm version
  ci/pipeline/dev_task_runner
  ci/pipeline/prod_task_runner
  ci/pipeline/qa_task_runner
  ci/pipeline/staging_task_runner
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/GeometryTransform.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
Labels: Batch to Run

#1492 DROTH-2332 Service road problems
  UI/src/assetTypeConfiguration.js
  UI/src/model/selectedLinearAsset.js
  UI/src/view/dynamicAssetForm.js
Labels: bug

#1493 DROTH-2344 (US 2142) Value field disappears
  UI/src/view/point_asset/servicePointForm.js
Labels: bug, urgent
