Repository finnishtransportagency/digiroad2, pull requests merged in 2020-07, with the labels that each got.

#1548 DROTH-2432 (US 2172) Traffic signs cannot yet to be added to pedestri…
  UI/src/view/point_asset/trafficSignForm.js
Labels: bug, merge ready

#1521 Droth 2280 changes on traffic lights by the new traffic law
  UI/images/center-marker-highlight.svg
  UI/src/application.js
  UI/src/assetTypeConfiguration.js
  UI/src/less/core/buttons.less
  UI/src/less/site/action-panel.less
  UI/src/less/site/asset-form.less
  UI/src/less/site/global.less
  UI/src/model/selectedPointAsset.js
  UI/src/utils/laneUtils.js
  UI/src/utils/validity-directions.js
  UI/src/view/autoGeneratedAssetsWorkList.js
  UI/src/view/navigationpanel/trafficLightBox.js
  UI/src/view/point_asset/directionalTrafficSignForm.js
  UI/src/view/point_asset/obstacleForm.js
  UI/src/view/point_asset/pointAssetForm.js
  UI/src/view/point_asset/pointAssetLayer.js
  UI/src/view/point_asset/pointAssetStyle.js
  UI/src/view/point_asset/railwayCrossingForm.js
  UI/src/view/point_asset/servicePointForm.js
  UI/src/view/point_asset/trafficLightForm.js
  UI/src/view/point_asset/trafficRegulationLayer.js
  UI/src/view/point_asset/trafficSignForm.js
  UI/test/integration-tests.html
  UI/tmpl/index.html
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
  digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataimport/CsvDataImporterSpec.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/TrafficLight.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/TrafficSign.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/asset/asset.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/Lane.scala
  digiroad2-oracle/src/main/resources/db/migration/V229__add_new_properties_to_traffic_lights_according_to_traffic_law_changes.sql
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/PointAssetOperations.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/PointAssetCsvImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/TrafficLightsCsvImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/TrafficSignCsvImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/Sequences.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OracleTrafficLightDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/queries.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/ObstacleService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/RailwayCrossingService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficLightService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficSignService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/MassTransitStopService.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficLightServiceSpec.scala
Labels: Flyway Version, merge ready

#1549 Droth 1921 automatic testing
  RobotProjectTest/Test/TestSuite/PedestrianCrossingTests.robot
  ci/config/Capfile
  ci/config/deploy.rb
  ci/pipeline/run_tests
Labels: merge ready

#1550 DROTH-2469 Private road data
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
Labels: merge ready, urgent

#1554 DROTH-2491 Lane dates are returning null value
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/lane/LaneDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/lane/LaneServiceSpec.scala
Labels: bug

#1553 DROTH-2488 Lane cut won't save properly
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/LaneFiller.scala
  digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/lane/LaneFillerSpec.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/lane/LaneServiceSpec.scala
Labels: bug
