Repository finnishtransportagency/digiroad2, pull requests merged in 2020-04, with the labels that each got.

#1497 DROTH-2352 - Road links don't show up when updating RoadDamagedByThaw
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/DynamicLinearAssetDao.scala
Labels: merge ready

#1503 Droth 2373 osgeo and opengeo repository switched
  ci/docker/Dockerfile.sbt
  ci/pipeline/fixture_reset
  java9-rt-export.jar
  project/build.properties
  project/build.scala
  sbt
  sbt-launch-lib.bash
  sbt-launch.jar
  sbt.bat
Labels: urgent

#1500 DROTH-2371 Digiroad2-api-error
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/VerificationDao.scala
Labels: bug, merge ready

#1501 DROTH-2374 Pop-up window shows up only for a few seconds and then dis…
  UI/src/view/municipalitySituationPopup.js
  UI/tmpl/index.html
Labels: bug, merge ready

#1502 DROTH-2375 Value field errors in Kalpa
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
  digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/IntegrationApiSpec.scala
Labels: bug

#1475 Droth 2244 lane information main lanes
  UI/csv_import.html
  UI/images/smallBlueLabeling.png
  UI/src/application.js
  UI/src/assetTypeConfiguration.js
  UI/src/authorizationpolicies/speedLimitAuthorizationPolicy.js
  UI/src/controller/laneModellingCollection.js
  UI/src/controller/linearAssetsCollection.js
  UI/src/controller/roadCollection.js
  UI/src/less/core/forms.less
  UI/src/less/site/action-panel.less
  UI/src/model/selectedLaneModelling.js
  UI/src/model/selectedLinearAsset.js
  UI/src/model/selectedLinkProperty.js
  UI/src/router.js
  UI/src/utils/backend-utils.js
  UI/src/utils/geometryUtils.js
  UI/src/utils/laneUtils.js
  UI/src/utils/property-utils.js
  UI/src/utils/roadAddressInfoPopup.js
  UI/src/view/dynamicAssetForm.js
  UI/src/view/linear_asset/laneModellingForm.js
  UI/src/view/linear_asset/laneModellingLabel.js
  UI/src/view/linear_asset/laneModellingLayer.js
  UI/src/view/linear_asset/laneModellingStyle.js
  UI/src/view/linear_asset/linearAssetLayer.js
  UI/src/view/linear_asset/speedLimitForm.js
  UI/src/view/linear_asset/speedLimitLayer.js
  UI/src/view/link_property/linkPropertyForm.js
  UI/src/view/navigationpanel/laneModellingBox.js
  UI/src/view/navigationpanel/speedLimitBox.js
  UI/src/view/point_asset/pointAssetForm.js
  UI/test/integration-tests.html
  UI/tmpl/index.html
  digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/dataimport/ImportDataApi.scala
  digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataimport/CsvDataImporterSpec.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/asset/asset.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/Lane.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/LaneFiller.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/LanePartitioner.scala
  digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/lane/LaneFillerSpec.scala
  digiroad2-oracle/src/main/resources/db/migration/V222__create_lane_asset.sql
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/viite/SearchViiteClient.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/LanesCsvImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/RoadLinkTempDAO.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/lane/LaneDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/middleware/DataImportManager.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadAddressService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/linearasset/LinearAssetService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/LaneUtils.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/lane/LaneServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/TierekisteriImporterOperationsSpec.scala
Labels: First to Deploy, Flyway Version

#1505 DROTH-2377 visual bug in municipality work-list
  UI/src/less/site/content-box.less
Labels: bug, merge ready

#1506 DROTH-2378_search_box_not_finding_bus_stops && DROTH-2381_search field doesn't find streets in some municipalities
  UI/src/model/locationSearch.js
  UI/src/utils/backend-utils.js
  UI/src/utils/locationInputParser.js
  UI/src/view/navigationpanel/searchBox.js
  UI/test/unit-tests/locationInputParserSpec.js
Labels: bug
