Repository finnishtransportagency/digiroad2, pull requests merged in 2020-05, with the labels that each got.

#1450 Droth 2119 mass transit stops and service points
  UI/images/add-point-asset-tool.svg
  UI/src/controller/massTransitStopsCollection.js
  UI/src/less/site/action-panel.less
  UI/src/less/site/asset-form.less
  UI/src/model/selectedMassTransitStop.js
  UI/src/router.js
  UI/src/utils/backend-utils.js
  UI/src/view/navigationpanel/actionPanelBox.js
  UI/src/view/navigationpanel/massTransitStopBox.js
  UI/src/view/point_asset/massTransitMarker.js
  UI/src/view/point_asset/massTransitStopForm.js
  UI/src/view/point_asset/massTransitStopLayer.js
  UI/src/view/providers/selectToolControl.js
  digiroad2-api-common/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Context.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
  digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/Digiroad2ApiSpec.scala
  digiroad2-oracle/src/main/resources/db/migration/V223__add_new_properties_to_mass_transit_stop_asset.sql
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/PointAssetOperations.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/AssetPropertyConfiguration.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/MassTransitStopDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/ServicePointBusStopDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/queries.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/MassTransitStopOperations.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/MassTransitStopService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/ServicePointStopService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/masstransitstop/TerminalBusStopStrategy.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/ServicePointStopServiceSpec.scala
Labels: Flyway Version, Second to Deploy, merge ready

#1508 DROTH-2383 Winter speed limit not working
  UI/src/view/linear_asset/piecewiseLinearAssetFormElements.js
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
Labels: bug, need changes

#1510 DROTH-2388 Possibility to insert invalid date-values for lane while e…
  UI/src/assetTypeConfiguration.js
Labels: bug

#1511 DROTH-2387 (US 2119) Bus stop symbols are not shown in legend
  UI/src/view/navigationpanel/massTransitStopBox.js
Labels: bug, merge ready

#1512 DROTH-2393 Quality error list empty
  UI/src/view/inaccurateWorkList.js
  UI/src/view/verificationWorkList.js
Labels: bug, merge ready

#1513 DROTH-2390 (US 2119) New bus stations, harbours etc. don't show added…
  UI/src/model/selectedMassTransitStop.js
  UI/src/view/point_asset/massTransitStopForm.js
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/ServicePointBusStopDao.scala
Labels: bug

#1494 Droth 2262 road traffic law changes for traffic signs
  UI/src/assetTypeConfiguration.js
  UI/src/less/core/forms.less
  UI/src/utils/validity-directions.js
  UI/src/view/point_asset/pointAssetForm.js
  UI/src/view/point_asset/trafficSignForm.js
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
  digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataimport/CsvDataImporterSpec.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/TrafficSign.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/asset/asset.scala
  digiroad2-oracle/src/main/resources/db/migration/V224__add_new_properties_according_to_traffic_law_changes.sql
  digiroad2-oracle/src/main/resources/db/migration/V225__add_start_end_property_trafficsign.sql
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/PointAssetCsvImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/TrafficSignCsvImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OracleTrafficSignDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/queries.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficSignService.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/SevenRestrictionsLimitationValidatorSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficSignServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/TrafficSignLinearGeneratorSpec.scala
Labels: Flyway Version, need changes

#1454 Droth 2224 date fields for traffic signs
  UI/src/assetTypeConfiguration.js
  UI/src/view/point_asset/pointAssetForm.js
  UI/src/view/point_asset/trafficSignForm.js
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
  digiroad2-oracle/src/main/resources/db/migration/V215__add_start_end_property_trafficsign.sql
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/PointAssetCsvImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/TrafficSignCsvImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OracleTrafficSignDao.scala
Labels: Flyway Version, US inside DROTH-2262 v2

#1514 Droth 2395 hover doesnt show lane info
  UI/src/utils/roadAddressInfoPopup.js
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
Labels: bug

#1509 Droth 2382 lane numbers on wrong track
  UI/src/controller/laneModellingCollection.js
  UI/src/utils/geometryUtils.js
  UI/src/view/linear_asset/laneModellingLabel.js
  UI/src/view/linear_asset/laneModellingStyle.js
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/asset/asset.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/LaneFiller.scala
  digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/lane/LaneFillerSpec.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/LaneUtils.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/lane/LaneServiceSpec.scala
Labels: bug

#1515 DROTH-2382 V2
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
Labels: bug

#1522 DROTH-2411 (U.S:2262)
  UI/src/assetTypeConfiguration.js
Labels: bug, merge ready
