Repository finnishtransportagency/digiroad2, pull requests merged in 2020-06, with the labels that each got.

#1527 DROTH-2402- Modifying assets in Ahvenanmaa
  UI/src/authorizationpolicies/authorizationPolicy.js
Labels: merge ready

#1486 Droth 2262 v2
  UI/src/application.js
  UI/src/assetTypeConfiguration.js
  UI/src/controller/roadCollection.js
  UI/src/controller/trafficSignsCollection.js
  UI/src/controller/trafficSignsReadOnlyCollection.js
  UI/src/router.js
  UI/src/view/autoGeneratedAssetsWorkList.js
  UI/src/view/point_asset/pointAssetLayer.js
  UI/src/view/point_asset/trafficSignForm.js
  UI/src/view/point_asset/trafficSignLayer.js
  UI/src/view/point_asset/trafficSignReadOnlyLayer.js
  UI/test/integration-tests.html
  UI/tmpl/index.html
  digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataimport/CsvDataImporterSpec.scala
  digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataimport/MassTransitStopCsvImporterSpec.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/TrafficSign.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/asset/asset.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/MassTransitStopCsvImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/ObstaclesCsvImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/PedestrianCrossingCsvImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/PointAssetCsvImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/RailwayCrossingCsvImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/ServicePointCsvImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/TrafficLightsCsvImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/TrafficSignCsvImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/pointasset/OracleTrafficSignDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/middleware/TrafficSignManager.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficSignService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/TrafficSignLinearGenerator.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficSignServiceSpec.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
Labels: Batch to Run, merge ready

#1451 Droth 2172 traffic control devices for pedestrian and cycleways
  UI/src/application.js
  UI/src/assetTypeConfiguration.js
  UI/src/controller/roadCollection.js
  UI/src/view/point_asset/pointAssetLayer.js
  UI/src/view/point_asset/trafficLayer.js
  UI/src/view/point_asset/trafficSignForm.js
  UI/tmpl/index.html
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/dataimport/ImportDataApi.scala
  digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataimport/CsvDataImporterSpec.scala
  digiroad2-api-oth/src/test/scala/fi/liikennevirasto/digiroad2/dataimport/MassTransitStopCsvImporterSpec.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/TrafficSign.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/MassTransitStopCsvImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/ObstaclesCsvImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/PedestrianCrossingCsvImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/PointAssetCsvImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/RailwayCrossingCsvImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/ServicePointCsvImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/TrafficLightsCsvImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/TrafficSignCsvImporter.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/RoadLinkService.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficSignServiceSpec.scala
Labels: US inside DROTH-2262 v2

#1519 DROTH-2404 corrections to trafficSignForm.js asset structure utilization
  UI/src/view/point_asset/trafficSignForm.js
Labels: Deploy after DROTH-2262v2

#1529 DROTH-2402 v2
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/user/User.scala
Labels: bug

#1530 DROTH-2428 Fixed moving old traffic signs
  UI/src/view/point_asset/trafficSignForm.js
Labels: bug

#1531 Droth 2426 lanes api error
  UI/src/less/site/global.less
  UI/src/model/selectedLaneModelling.js
  UI/src/view/linear_asset/laneModellingForm.js
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/lane/LaneDao.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/LaneUtils.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/lane/LaneServiceSpec.scala
Labels: bug

#1532 DROTH-2430 Correction of side lanes positioning
  UI/src/utils/laneUtils.js
  UI/src/view/linear_asset/laneModellingStyle.js
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/LaneFiller.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
Labels: bug

#1534 DROTH-2425 Weekly batch process failing on data validators
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/IntegrationApi.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/TrafficSign.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/asset/asset.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/Lane.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/pointasset/TrafficSignService.scala
Labels: bug, merge ready

#1535 DROTH-2432 (US 2172) Traffic signs cannot yet to be added to pedestri…
  UI/src/assetTypeConfiguration.js
  UI/src/controller/roadCollection.js
  UI/src/controller/trafficSignsRoadCollection.js
  UI/test/integration-tests.html
  UI/tmpl/index.html
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/TrafficSignCsvImporter.scala
Labels: bug, merge ready

#1536 DROTH-2434 Change bus stop names
  UI/src/view/navigationpanel/massTransitStopBox.js
  UI/test/unit-tests/selectedMassTransitStopSpec.js
  UI/test_data/enumeratedPropertyValuesTestData.js
  digiroad2-oracle/src/main/resources/db/migration/V227__update_bus_stop_names.sql
Labels: Flyway Version, merge ready, urgent

#1538 DROTH-2440 Additional lane is shown as whole even though it is cut
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/LanePartitioner.scala
Labels: bug, merge ready

#1537 DROTH-2435 Operator_and_municipality_users_cannot_edit_points_on_Ahvenanmaa_state_roads
  UI/src/authorizationpolicies/authorizationPolicy.js
  UI/src/authorizationpolicies/massTransitStopAuthorizationPolicy.js
  UI/src/authorizationpolicies/pointAssetAuthorizationPolicy.js
  UI/src/authorizationpolicies/pointStateRoadAuthorizationPolicy.js
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/user/User.scala
Labels: bug, merge ready

#1542 Droth 2438 some errors found from the speed limit work list for municipality user
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/linearasset/RoadLink.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/dao/linearasset/OracleSpeedLimitDao.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/DataFixture.scala
Labels: bug

#1543 Droth 2439 problems with additional lanes when changing the direction main lane
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/Lane.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/service/lane/LaneService.scala
Labels: bug

#1544 DROTH-2426 Lanes: API error in QA
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/LaneFiller.scala
  digiroad2-geo/src/test/scala/fi/liikennevirasto/digiroad2/lane/LaneFillerSpec.scala
Labels: bug, merge ready

#1545 DROTH-2445 Errors in mass restrictions from Tierekisteri
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/client/tierekisteri/importer/TierekisteriPointConversionImporter.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/util/TierekisteriPointConversionImporterSpec.scala
Labels: bug, merge ready

#1546 DROTH-2437 (US 2218) Roadworks are not created from traffic signs
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/middleware/TrafficSignManager.scala
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/util/TrafficSignLinearGenerator.scala
Labels: bug, merge ready

#1533 Droth 2370 ui changes to the lanetool
  UI/src/assetTypeConfiguration.js
  UI/src/less/core/forms.less
  UI/src/less/site/action-panel.less
  UI/src/model/selectedLaneModelling.js
  UI/src/view/dynamicAssetForm.js
  UI/src/view/linear_asset/laneModellingForm.js
  UI/src/view/linear_asset/laneModellingStyle.js
  UI/src/view/navigationpanel/laneModellingBox.js
  digiroad2-api-oth/src/main/scala/fi/liikennevirasto/digiroad2/Digiroad2Api.scala
  digiroad2-geo/src/main/scala/fi/liikennevirasto/digiroad2/lane/Lane.scala
  digiroad2-oracle/src/main/resources/db/migration/V228__remove_lane_continuity_and_information_from_db.sql
  digiroad2-oracle/src/main/scala/fi/liikennevirasto/digiroad2/csvDataImporter/LanesCsvImporter.scala
  digiroad2-oracle/src/test/scala/fi/liikennevirasto/digiroad2/service/lane/LaneServiceSpec.scala
Labels: First to Deploy, Flyway Version, merge ready
